apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig


metadata:
  name: adamscluster
  region: ap-south-1


nodeGroups:
   - name: ng1
     desiredCapacity: 3
     instanceType: t2.micro
     ssh:
        publicKeyName: EKS
   - name: ng2
     desiredCapacity: 3
     instanceType: t2.small
     ssh:
        publicKeyName: EKS   
   - name: ng3
     desiredCapacity: 4
     instanceType: t2.medium
     ssh:
        
        publicKeyName: EKS
